--INSERT STATUS
INSERT INTO TAB_STATUS (DESCRICAO) VALUES ('ABERTO');
INSERT INTO TAB_STATUS (DESCRICAO) VALUES ('DEFERIDO');
INSERT INTO TAB_STATUS (DESCRICAO) VALUES ('INDEFERIDO');

--INSERT PAPEL
INSERT INTO TAB_ROLE (NOME) VALUES ('ADMIN');
INSERT INTO TAB_ROLE (NOME) VALUES ('PROFESSOR');